Author = "lluck42"
Copyright = "lluck42"
baseURL = "https://lluck42.gitee.io"
languageCode = "en-us"
theme = "ananke"
title = "lluck42个人博客"
summaryLength = 20

[params]
description = "Tesla's Aweso22me Hugo Site"
mainSections = ["note"]
